# frozen_string_literal: true

plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/*_schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/initializers/new_framework_defaults_*.rb"

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Lint/EmptyBlock:
  Exclude:
    - "config/routes.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"
    - "db/migrate/**/*"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"
    - "db/migrate/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5
